# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-11 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_auto_20160408_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='published_at',
            field=models.DateTimeField(null=True),
        ),
    ]
