# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-11 18:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_auto_20160411_2124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channelstatistics',
            old_name='subsciber_count',
            new_name='subscriber_count',
        ),
    ]
