# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-20 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0005_auto_20160411_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
