# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-01 09:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0006_auto_20160420_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videostatistics',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='stats.Video'),
        ),
    ]
