# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 19:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChannelStatistics',
            new_name='ChannelStats',
        ),
        migrations.RenameModel(
            old_name='VideoStatistics',
            new_name='VideoStats',
        ),
        migrations.AlterField(
            model_name='video',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='channel.Channel'),
        ),
    ]
