# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 19:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0002_auto_20160526_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='videostats',
            name='channel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='channel.Channel'),
            preserve_default=False,
        ),
    ]
